version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/labs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    groups:
      pre-commit-hooks:
        patterns: ["*"]
    cooldown:
      default-days: 7
